export { default as ElectionPage } from './ElectionPage.vue'
export { default as RestaurantPage } from './RestaurantPage.vue'
export { default as BarPage } from './BarPage.vue'
export { default as UploadPage } from './UploadPage.vue'
export { default as BuploadPage } from './BuploadPage.vue'
export { default as NotFound } from './NotFound.vue'
export { default as LoginPage } from './LoginPage.vue'
export { default as ConfirmationPage } from './ConfirmPage.vue'